### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined client/all servers tabs

### ISSUE THREAD

**Issue by si458** [Devolutions/WaykDen-ps#102]
just updated my WaykDen server using latest git
which has pulled the latest image`devolutions/den-server:2.4.0-buster`
but not the web panel is unusable?
`Chrome 83.0.4103.116 OSX 10.15.5`
it loads the `dashboard` fine with no errors
but then `Clients` and `All Servers` tabs are displaying this undefined error
```
Cannot read property 'toLowerCase' of undefined
Client error
TypeError: Cannot read property 'toLowerCase' of undefined
    at t.getOsIcon (https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:76922)
    at new t (https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:76837)
    at e.t.fromMachine (https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:198468)
    at e.t (https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:198369)
    at new e (https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:198877)
    at https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:208912
    at Array.map (<anonymous>)
    at e.project (https://remote.xxxxx.com/web/5.591e92a37b63d752a8b0.js:1:208888)
    at e._next (https://remote.xxxxx.com/web/main.677a2a484c1c4c4e03d2.js:1:399876)
    at e.next (https://remote.xxxxx.com/web/main.677a2a484c1c4c4e03d2.js:1:738668)
```

**Comment by ngirot-devolutions** [comment]
Hi Simon,

Thank you for your feedback,
I'm really sorry for the inconvenience. I'm working on a fix and we will publish a new version as soon as possible. 
I will update that issue when it will be released

**Comment by si458** [comment]
> Hi Simon,
> 
> 
> 
> Thank you for your feedback,
> 
> I'm really sorry for the inconvenience. I'm working on a fix and we will publish a new version as soon as possible. 
> 
> I will update that issue when it will be released 

Hi

Thanks for this...

Is the anyway to roll back a version?
Or undo the latest git pull that uses the newer image?

**Comment by ngirot-devolutions** [comment]
If you have a backup of your database yes, otherwise the database got to many modification to rollback safely in another version. I try to do my best to fix the issue the quick as i can.

**Comment by si458** [comment]
Ok no worries, leave it with you :)
Is it the same issue with Firefox? #102

**Comment by ngirot-devolutions** [comment]
I'm pretty sure it is the same issue.

I tried to reproduce something similar with bad data without success. But I wrote safer code to try to avoid that error. We built a new "dev" image and to be sure that it fixes your issue, I would like if you could test it. If you can confirm that it fixes the issue, we will make an official image and an official WaykDen version.

To do that just execute the following command in your WaykDen configuration folder :
`Set-WaykDenConfig -ServerImage devolutions/den-server:2.5.0-buster-dev`

After your test, you should remove that configuration because you will stay on that specific build forever. To remove that configuration after, just run that command :
`Set-WaykDenConfig -ServerImage ""`
And we don't recomment user to use our dev version since you could get some weird behavior. So if you could confirm if it fix or not, we would appreciate.

Thanks !

**Comment by si458** [comment]
@ngirot-devolutions please forgive my delay, ive only just seen this message!

i have tried that new image and seems to be fine now, no errors both in firefox and chrome!

only issue i have now found is the OS columns on those tabs are now only showing 10-12 characters?

they are showing `Windows 10 P  Windows 10 H  Windows S` etc
instead of `Windows 10 Pro  Windows 10 Home  Windows Server 2019` etc...

**Comment by ngirot-devolutions** [comment]
I'm glad to see the problem solved. Thank you for your help. 
A new version will be published with those fixes soon. I will let you know here when it will be done
I've also fixed the Wayk Now UA parsing issue - thanks for reporting.

**Comment by si458** [comment]
@ngirot-devolutions erm oops another browser error in the 'all servers' tab this time with Safari on OSX
`
Uncaught (in promise): ReferenceError: Can't find variable: BroadcastChannel t@https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1934095 factory@https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1936686 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1083720 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1081371 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1081414 cn@https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1037517 https://remote.xxx.com/web/5.22d45eaf3708217515c2.js:1:297221 hn@https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1038312 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1128367 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1128428 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1128706 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:1071706 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:622332 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:576791 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:575786 forEach@[native code] https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:575756 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:576130 https://remote.xxx.com/web/main.af6a5357501fd69bc09d.js:1:575786 forEach@[native code] `

**Comment by ngirot-devolutions** [comment]
Sorry for the inconvenience but for now Safari is not supported mainly because of the leak of support for BroadcastChannel (also Internet Explorer).

**Comment by ngirot-devolutions** [comment]
Also we published a new official version : https://www.powershellgallery.com/packages/WaykDen/2020.2.2 
Don't forget to remove the specific configuration you did to get the dev version of den-server by executing the following command: Set-WaykDenConfig -ServerImage ""
Thank you again and let me know if everything is ok.

**Comment by si458** [comment]
@ngirot-devolutions 
i had already pulled the latest git repo down a few mins after you updated it (i have watch enabled 🤣)
all seems well apart from the safari issue but that doesnt matter for now
it was mainly my ipad i was using it on but then i realised i had the wayknow app installed and wondered why i was using the web client 😆 

only other weird issue i have noticed is the Web Client, every so often when i try to connect to a client, it just says `Internal Server Error 500 please check server logs` but when checking the logs, all it shows is `TIME+DATE https://remote.xxx.com/{BLABLABLA}/initialize 500` ? but i will open separate issue for this

**Comment by si458** [comment]
> Sorry for the inconvenience but for now Safari is not supported mainly because of the leak of support for BroadcastChannel (also Internet Explorer).

Have you tried these polyfills for BroadcastChannel?

https://github.com/JSmith01/broadcastchannel-polyfill


https://github.com/pubkey/broadcast-channel

It's really annoying because I don't always have the id numbers to hand so I normally just login on web panel and go into the all servers tab and get the id number, but I can't do that on my iPad :(

**Comment by ngirot-devolutions** [comment]
Hi @si458
Sorry for the delay. Actually, the web client is still in beta but i will check this polyfills soon if it's important for you for sure. Thanks for the links. I will tell you the day where we have something working with Safari.

**Comment by si458** [comment]
> Hi @si458
> 
> Sorry for the delay. Actually, the web client is still in beta but i will check this polyfills soon and for sure, if it's important for you, we will find a solution. Thanks for the links. I will tell you the day where we have something working with Safari.

Hi
It's only import for myself because I don't always have the id numbers to hand as explained, and the staff are to stubborn to open the app up and give me the id number, so I normally go into the online list, look for the comps name (as I name the comps and I no which pc there normally on) and then copy/paste it into wayknow on my iPad and then connect

But thank you for looking into this tho!
