### ISSUE TITLE
kubernetes yaml support maybe

### ISSUE THREAD

**Issue by si458** [Devolutions/WaykDen-ps#107]
it would be amazing if the was a function that could generate individual kubernetes yaml files for us

or even some samples of how to deploy it to kubernetes

im looking at moving all our individual docker hosts (about 10 little vms) into a kubernetes cluster (3 powerful vms)

**Comment by awakecoding** [comment]
If you take a look at the structure of the PowerShell code, we generate the docker commands on the fly, and nothing would prevent you from writing code to try and generate the Kubernetes yaml files. Making this easier was one of the goals of the current structure, but we are still a long way from getting to support Kubernetes export in WaykDen-ps. If you get reasonably comfortable with it, maybe just give it a shot.

**Comment by awakecoding** [comment]
@si458 if you don't mind, I will close this issue, but feel free to open a pull request if you wish.
