### ISSUE TITLE
Newbie - and things just aren't working

### ISSUE THREAD

**Issue by christinerutter** [Devolutions/WaykDen-ps#66]
I have followed the intructions on https://github.com/devolutions/WaykDen-ps.
Installed & Imported the ps module
Installed docker
Initiated Hyper V as I am running it on a win 10 client
Confirmed by docker run hello-world - got no errors
Went through the config including an ext address, registered the cert relating to that ext address
Put the relay in
Didn't have a db, so allowed it to generate one
When I try and start-waykden

PS C:\Users\christineruttera> start-waykden
docker pull library/mongo:4.2-windowsservercore-1809
docker : no matching manifest for linux/amd64 in the manifest list entries
At line:1 char:1
+ docker pull library/mongo:4.2-windowsservercore-1809
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (no matching man...st list entries:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker pull devolutions/picky:4.2.1-servercore-ltsc2019
docker : image operating system "windows" cannot be used on this platform
At line:1 char:1
+ docker pull devolutions/picky:4.2.1-servercore-ltsc2019
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (image operating...n this platform:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker pull devolutions/den-lucid:3.6.5-servercore-ltsc2019
docker : image operating system "windows" cannot be used on this platform
At line:1 char:1
+ docker pull devolutions/den-lucid:3.6.5-servercore-ltsc2019
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (image operating...n this platform:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker pull devolutions/den-server:1.14.0-servercore-ltsc2019
docker : image operating system "windows" cannot be used on this platform
At line:1 char:1
+ docker pull devolutions/den-server:1.14.0-servercore-ltsc2019
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (image operating...n this platform:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker pull library/traefik:1.7-windowsservercore-1809
docker : no matching manifest for linux/amd64 in the manifest list entries
At line:1 char:1
+ docker pull library/traefik:1.7-windowsservercore-1809
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (no matching man...st list entries:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker : Error response from daemon: plugin "nat" not found
At C:\Program Files\WindowsPowerShell\Modules\WaykDen\2020.1.4\Private\DockerHelper.ps1:235 char:15
+         $Id = docker $cmd
+               ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ..."nat" not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Starting den-mongo
docker : Unable to find image 'mongo:4.2-windowsservercore-1809' locally
At line:1 char:1
+ docker run --name den-mongo -d --network=den-network -v den-mongodata ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to find ...e-1809' locally:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
4.2-windowsservercore-1809: 
Pulling from library/mongo
C:\Program Files\Docker\Docker\resources\bin\docker.exe: no matching manifest for linux/amd64 in the manifest 
list entries.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
docker : Error: No such object: den-mongo
At C:\Program Files\WindowsPowerShell\Modules\WaykDen\2020.1.4\Private\DockerHelper.ps1:129 char:18
+     $running = $(docker inspect -f '{{.State.Running}}' $Name)
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: No such object: den-mongo:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error starting den-mongo
At C:\Program Files\WindowsPowerShell\Modules\WaykDen\2020.1.4\Public\WaykDenService.ps1:466 char:9
+         throw "Error starting $($Service.ContainerName)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error starting den-mongo:String) [], RuntimeException
    + FullyQualifiedErrorId : Error starting den-mongo

**Comment by awakecoding** [comment]
Hi,

Since you are using Windows 10, and therefore Docker Desktop for Windows, you need to switch to Windows containers before launching Wayk Den: https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

We will add a note in the guide for Windows 10.

**Comment by christinerutter** [comment]
thanks - just switched, and trying again

**Comment by christinerutter** [comment]
Thank you - looks like I am running - although can't get to the localhost:4000 
![image](https://user-images.githubusercontent.com/62559695/77400643-66cc8e00-6da3-11ea-8654-da7da6374c39.png) are the powershell outputs

![image](https://user-images.githubusercontent.com/62559695/77400705-7fd53f00-6da3-11ea-8803-0a6f2a13af13.png)
Is the response from localhost:4000

Anymore advice would be gratefully received

**Comment by cocoon** [comment]
Hi, just for testing it was working for me to change the listener to https://fqdn

**Comment by awakecoding** [comment]
@christinerutter if you wish to test everything in localhost, then the ExternalUrl should match your ListenerUrl, since we should always access Wayk Den through the ExternalUrl. A quick test is to do a Set-WaykDenConfig -ListenerUrl http://localhost:4000 -ExternalUrl http://localhost:4000. The best way, however, is to use the intended final external url. We'd expect a few people to make the mistake of accessing Wayk Den through the listener url rather than the external url, so we're looking into ways to catch this error and present a more meaningful error message. Thank you for testing, there are a few pitfalls like this one we need to find ways to prevent.

**Comment by christinerutter** [comment]
tried setting it up again in a new folder, and now getting a new error :)

PS C:\data\WaykDen\ver3> New-WaykDenConfig -Realm jamesvillas.net -externalurl http://localhost:4000 -ListenerUrl http://localhost:4000

PS C:\data\WaykDen\ver3> Import-WaykDenCertificate -CertificateFile 'C:\Data\WaykDen\jamesvillas-net-chain.pem' -PrivateKeyFile 'C:\Data\WaykDen\jamesvillas.net.key'

PS C:\data\WaykDen\ver3> Set-WaykDenConfig -JetRelayUrl https://api.jet-relay.net

PS C:\data\WaykDen\ver3> Start-WaykDen
docker pull library/mongo:4.2-windowsservercore-1809
docker pull devolutions/picky:4.2.1-servercore-ltsc2019
docker pull devolutions/den-lucid:3.6.5-servercore-ltsc2019
docker pull devolutions/den-server:1.14.0-servercore-ltsc2019
docker pull library/traefik:1.7-windowsservercore-1809
docker rm den-mongo
Starting den-mongo
docker : C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: hcsshim::CreateComputeSystem 28a6f64d8227e9d6e376f817d07ffc6d8dd0737ebba8e538f9fada63944ce53e: Logon failure: the user has not been granted the 
requested logon type at this computer.
At line:1 char:1
+ docker run --name den-mongo -d --network=den-network -v den-mongodata ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File... this computer.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
(extra info: {"SystemType":"Container","Name":"28a6f64d8227e9d6e376f817d07ffc6d8dd0737ebba8e538f9fada63944ce53e","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\28a6f64d8227e9d6e37
6f817d07ffc6d8dd0737ebba8e538f9fada63944ce53e","Layers":[{"ID":"47eaeb71-0eff-5cf6-bbc5-5e9d96b8a333","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0126c425b2c10f257c9f2e158b77e5622acd73c4c8cd435486b299b821237fb8"},{"ID":"a35ac599-6b89-5
d8f-8ec8-2dc83a71ef50","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6f6dd48992730c3315fb378477b1985b7b6f9c261aa740c23aedc56037c80a9d"},{"ID":"86c86951-bbc2-52c1-9a51-1a7f6fe6a950","Path":"C:\\ProgramData\\Docker\\windowsfilter\\de1de6ef
e331fa21b07684059e9ca9f9a8747eff9950d27897575ad2bec33aae"},{"ID":"93752350-4e8a-541e-b717-07448a73a0bf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c5adbfb3d79edf33ef55af6bf2c4a878ff0316a5a4fe49529e11fb5547c1c4ee"},{"ID":"b64f1694-6c1c
-59f6-9003-5d708bee61f7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\46661fb1521a1c673a633822476ca5923410e2238bd7b394278c8c376aae6181"},{"ID":"680c551c-18b6-56bb-91de-ccf413a3e92d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ee9636
54ee1dcb6ad0eee4bcc9ab2fd6843ddffa4aaf03f88a48f4b1f579f38d"},{"ID":"48089ba6-5f1e-5364-8859-b084908e08ea","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5a8ae3014e88ca033df4fbab9ad723501e63bf2348d4df33f3ea5c256659c6c8"},{"ID":"cbf86044-96
b7-51c5-a4d0-422c5eb04d1c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1696f767a19afe6a78706d4fe24ffb2949ec824a0b3af1c1ee36242f273f0575"},{"ID":"36cb81e8-551e-55ea-83f7-76a970ae9a8d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\359d
b684011a0ed68a923610b7df25da8b4108d452968e0308b751a366c60527"},{"ID":"d6d8d439-3742-55c6-8111-16ca3b3a591a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eb2d38c4c056744192440b3275463b280fd3c069510339f82e50388c74222fbe"}],"HostName":"28a
6f64d8227","MappedDirectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\den-mongodata\\_data","ContainerPath":"c:\\data\\db","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramDa
ta\\Docker\\volumes\\e672eff25710472c742bf1a8fec1eb7a9aa76a2cd1d5a817ac834c481a28575b\\_data","ContainerPath":"c:\\data\\configdb","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"Endpoi
ntList":["A81A6B3E-9C4A-43E7-988B-EE8E868B6CFA"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\359db684011a0ed68a923610b7df25da8b4108d452968e0308b751a366c60527\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).
Error starting den-mongo
At C:\Program Files\WindowsPowerShell\Modules\WaykDen\2020.1.4\Public\WaykDenService.ps1:466 char:9
+         throw "Error starting $($Service.ContainerName)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error starting den-mongo:String) [], RuntimeException
    + FullyQualifiedErrorId : Error starting den-mongo

**Comment by awakecoding** [comment]
this looks like an intermittent issue with the latest version of Docker Desktop for Windows: https://github.com/docker/for-win/issues/3542

This is why Windows 10 should only be used for testing, not production use cases. If you have a Windows Server 2019 iso, I would recommend using it, since it works with the Microsoft docker provider that doesn't use Docker Desktop for Windows.

**Comment by christinerutter** [comment]
We just want to test and see that it can do what we want it to.

Would it work if I was to spin up a server 2019 vm and run it from that?

Thanks

Christine Rutter
Lead Service Desk Engineer

**Comment by awakecoding** [comment]
Yes, absolutely. Windows 10 + Docker Desktop for Windows is really there to let people test on their laptops, but real production use cases should always be done inside a Windows Server 2019 virtual machine, or with an Ubuntu virtual machine. Windows is correctly supported with Windows containers, just make sure to follow the instructions to install the Microsoft docker provider and not Docker desktop for Windows in Windows server.

https://github.com/devolutions/WaykDen-ps#windows-server-2019
https://github.com/Devolutions/WaykDen-ps/blob/master/docs/getting-started-azure.adoc

The Azure VM guide can still be a good reference for Windows Server 2019. The base image used in the Azure VM is simply Windows Server 2019 Core + Containers, but you can get the same in a virtual machine which you install the Windows container feature.

**Comment by awakecoding** [comment]
@christinerutter I suggest closing this issue for now, but feel free to either re-open a new issue or contact me at wayk@devolutions.net such that I can continue assisting you.
