### ISSUE TITLE
JetRelay is attached to bridge instead of den-network

### ISSUE THREAD

**Issue by si458** [Devolutions/WaykDen-ps#96]
JetRelay is attached to dockers default bridge instead of the den-network

is it possible to change this or for me to change it some how?

im trying to get traefik to proxy https and wss to http://devolutions-jet:7171 but it cant resolve devolutions-jet container because its on another network

**Comment by awakecoding** [comment]
@si458 sorry I didn't get any sooner. Adding devolutions-jet to the same docker network (called "den-network") should be relatively easy. You can modify the code in Get-JetService to add "den-network" to the Networks property like we do in the other Wayk Den containers: https://github.com/Devolutions/WaykDen-ps/blob/master/WaykDen/Public/WaykDenService.ps1#L306

However, you would then need to modify the code that generates the traefik.toml configuration file. This file is generated and overwritten every time Start-WaykDen is called, so you could try temporarily removing the line that overwrites it and try modifying the configuration file (https://github.com/Devolutions/WaykDen-ps/blob/master/WaykDen/Public/WaykDenService.ps1#L629)

I can see what you are trying to achieve, but I am unsure about the best way to approach this. We could try adding the jet such that it is managed like the rest of the Wayk Den containers, but then it wouldn't be so isolated from the rest, which may make it even more confusing when trying to manage it separately afterwards. Nevertheless, feel free to experiment and try making it work the way you'd like.

**Comment by si458** [comment]
@awakecoding forgive my delay, this slipped past me...

ive had a think and you are possibly right,
you need to keep the waykden and the jetrelay seperate as they do seperate things and you dont always need your own jetreley

i came across this docker host port redirecter which seems to do the trick for the moment!
https://github.com/qoomon/docker-host

simply diverted my traefik to the docker-host container port 7171 which then diverts the port 7171 to the docker host port 7171 itself, which the jet-relay is listening on anyways

its a step inbetween to make things go wrong, but it does the trick for now :)

**Comment by si458** [comment]
@awakecoding ok found another way which avoids the middle container
traefik actually states it on there networking page but didnt realise it was simple to just add the dns entry via dockers extra_hosts (https://docs.traefik.io/providers/docker/#host-networking)
```
extra_hosts:
  - "host.docker.internal:172.17.0.1"
```
